[workspace]
members = [
  "crates/foundation",
  "crates/binary-config-parser",

  "servers/browser-server",
  "servers/lobby-server",
  "servers/login-server",
  "servers/match-server",

  "scripts/binary-config-cli",
]
exclude = []
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
actix-web = "4.10.2"
arrayref = "0.3.9"
bytemuck = { version = "1.23.1", features = ["derive", "min_const_generics"] }
clap = { version = "4.4", features = ["derive"] }
crc32fast = "1.4.2"
encoding_rs = "0.8.35"
env_logger = "0.10"
log = "0.4"
num-derive = "0.4"
num-traits = "0.2"
openssl = "0.10"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["std"] }
sqlx = { version = "0.8", features = [ "runtime-tokio" ] }
thiserror = "2.0.12"

foundation = { path = "crates/foundation" }
binary-config-parser = { path = "crates/binary-config-parser" }

[workspace.lints.clippy]
