[package]
name = "pdb-parser"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true }

pdb = { package = "pdb2", git = "https://github.com/afranchuk/pdb", rev = "384c165" }

pdb-addr2line-orig = { package = "pdb-addr2line", version = "0.11.2" }
pdb-addr2line = { git = "https://github.com/srp-survarium/pdb-addr2line", rev = "cfe5fab" }

[lints]
workspace = true
