void __thiscall vostok::network_core::udp_match_connection::channel::~channel(
        vostok::network_core::udp_match_connection::channel *this)
{
  boost::intrusive::set<vostok::network_core::udp_match_message_part,boost::intrusive::member_hook<vostok::network_core::udp_match_message_part,boost::intrusive::set_member_hook<boost::intrusive::none,boost::intrusive::none,boost::intrusive::none,boost::intrusive::none>,0>,boost::intrusive::compare<vostok::network_core::udp_match_packet::part_id_comparer>,boost::intrusive::none,boost::intrusive::none> *v2; // ecx

  boost::intrusive::set<vostok::network_core::udp_match_packet,boost::intrusive::member_hook<vostok::network_core::udp_match_packet,boost::intrusive::set_member_hook<boost::intrusive::none,boost::intrusive::none,boost::intrusive::none,boost::intrusive::none>,20>,boost::intrusive::compare<vostok::network_core::udp_match_packet::comparer>,boost::intrusive::none,boost::intrusive::none>::~set<vostok::network_core::udp_match_packet,boost::intrusive::member_hook<vostok::network_core::udp_match_packet,boost::intrusive::set_member_hook<boost::intrusive::none,boost::intrusive::none,boost::intrusive::none,boost::intrusive::none>,20>,boost::intrusive::compare<vostok::network_core::udp_match_packet::comparer>,boost::intrusive::none,boost::intrusive::none>(
    (boost::intrusive::set<vostok::network_core::udp_match_message_part,boost::intrusive::member_hook<vostok::network_core::udp_match_message_part,boost::intrusive::set_member_hook<boost::intrusive::none,boost::intrusive::none,boost::intrusive::none,boost::intrusive::none>,0>,boost::intrusive::compare<vostok::network_core::udp_match_packet::part_id_comparer>,boost::intrusive::none,boost::intrusive::none> *)this,
    &this->multipackets.tree_.data_.node_plus_pred_.header_plus_size_.size_);
  boost::intrusive::set<vostok::network_core::udp_match_packet,boost::intrusive::member_hook<vostok::network_core::udp_match_packet,boost::intrusive::set_member_hook<boost::intrusive::none,boost::intrusive::none,boost::intrusive::none,boost::intrusive::none>,20>,boost::intrusive::compare<vostok::network_core::udp_match_packet::comparer>,boost::intrusive::none,boost::intrusive::none>::~set<vostok::network_core::udp_match_packet,boost::intrusive::member_hook<vostok::network_core::udp_match_packet,boost::intrusive::set_member_hook<boost::intrusive::none,boost::intrusive::none,boost::intrusive::none,boost::intrusive::none>,20>,boost::intrusive::compare<vostok::network_core::udp_match_packet::comparer>,boost::intrusive::none,boost::intrusive::none>(
    v2,
    this);
}
