vostok::render::bake_decal_cook *__thiscall vostok::render::bake_decal_cook::`vector deleting destructor'(
        vostok::render::bake_decal_cook *this,
        char a2)
{
  stlp_std::priv::_Rb_tree<vostok::render::rt_cache::coord_type,stlp_std::less<vostok::render::rt_cache::coord_type>,stlp_std::pair<vostok::render::rt_cache::coord_type const,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy>>,stlp_std::priv::_Select1st<stlp_std::pair<vostok::render::rt_cache::coord_type const,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy>>>,stlp_std::priv::_MapTraitsT<stlp_std::pair<vostok::render::rt_cache::coord_type const,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy>>>,vostok::render::std_allocator<stlp_std::pair<vostok::render::rt_cache::coord_type,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy>>>>::~_Rb_tree<vostok::render::rt_cache::coord_type,stlp_std::less<vostok::render::rt_cache::coord_type>,stlp_std::pair<vostok::render::rt_cache::coord_type const,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy>>,stlp_std::priv::_Select1st<stlp_std::pair<vostok::render::rt_cache::coord_type const,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy>>>,stlp_std::priv::_MapTraitsT<stlp_std::pair<vostok::render::rt_cache::coord_type const,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy>>>,vostok::render::std_allocator<stlp_std::pair<vostok::render::rt_cache::coord_type,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy>>>>(
    (stlp_std::priv::_Rb_tree<vostok::render::surfaces_cache::coord_type,stlp_std::less<vostok::render::surfaces_cache::coord_type>,stlp_std::pair<vostok::render::surfaces_cache::coord_type const ,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy> >,stlp_std::priv::_Select1st<stlp_std::pair<vostok::render::surfaces_cache::coord_type const ,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy> > >,stlp_std::priv::_MapTraitsT<stlp_std::pair<vostok::render::surfaces_cache::coord_type const ,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy> > >,vostok::render::std_allocator<stlp_std::pair<vostok::render::surfaces_cache::coord_type,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy> > > > *)this,
    (stlp_std::priv::_Rb_tree<vostok::render::surfaces_cache::coord_type,stlp_std::less<vostok::render::surfaces_cache::coord_type>,stlp_std::pair<vostok::render::surfaces_cache::coord_type const ,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy> >,stlp_std::priv::_Select1st<stlp_std::pair<vostok::render::surfaces_cache::coord_type const ,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy> > >,stlp_std::priv::_MapTraitsT<stlp_std::pair<vostok::render::surfaces_cache::coord_type const ,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy> > >,vostok::render::std_allocator<stlp_std::pair<vostok::render::surfaces_cache::coord_type,vostok::intrusive_ptr<vostok::render::render_target,vostok::render::resource_intrusive_base,vostok::threading::single_threading_policy> > > > *)&this->m_surfaces_cache);
  this->__vftable = (vostok::render::bake_decal_cook_vtbl *)&vostok::resources::cook_base::`vftable';
  if ( (a2 & 1) != 0 )
    operator delete(this);
  return this;
}
