void __thiscall Scaleform::Render::GlyphQueue::GlyphQueue(Scaleform::Render::GlyphQueue *this)
{
  this->MinSlotSpace = 10;
  this->FirstTexture = 0;
  this->NumTextures = 0;
  this->TextureWidth = 0;
  this->TextureHeight = 0;
  this->MaxSlotHeight = 0;
  this->NumBandsInTexture = 0;
  this->Slots.FirstPage = 0;
  this->Slots.LastPage = 0;
  this->Slots.NumElementsInPage = 127;
  this->Slots.FirstEmptySlot = 0;
  this->Slots.pHeapOrPtr = &this->Slots;
  this->SlotQueue.Root.pPrev = (Scaleform::Render::GlyphSlot *)&this->SlotQueue;
  this->SlotQueue.Root.pNext = (Scaleform::Render::GlyphSlot *)&this->SlotQueue;
  this->SlotQueueSize = 0;
  this->ActiveSlots.Root.TextFields.Root.pPrev = (Scaleform::Render::TextNotifier *)&this->ActiveSlots.Root.TextFields;
  this->ActiveSlots.Root.TextFields.Root.pNext = (Scaleform::Render::TextNotifier *)&this->ActiveSlots.Root.TextFields;
  this->ActiveSlots.Root.SlotFence.pObject = 0;
  this->ActiveSlots.Root.pPrevActive = &this->ActiveSlots.Root;
  this->ActiveSlots.Root.pNextActive = &this->ActiveSlots.Root;
  this->Glyphs.FirstPage = 0;
  this->Glyphs.LastPage = 0;
  this->Glyphs.NumElementsInPage = 127;
  this->Glyphs.FirstEmptySlot = 0;
  this->Glyphs.pHeapOrPtr = &this->Glyphs;
  this->Bands.Data = 0;
  this->Bands.Size = 0;
  this->Bands.Capacity = 0;
  this->GlyphHTable.mHash.pTable = 0;
  this->NumUsedBands = 0;
  this->Notifiers.FirstPage = 0;
  this->Notifiers.LastPage = 0;
  this->Notifiers.NumElementsInPage = 127;
  this->Notifiers.FirstEmptySlot = 0;
  this->Notifiers.pHeapOrPtr = &this->Notifiers;
  this->pEvictNotifier = 0;
}
